### ISSUE TITLE
List Serialization not work

### ISSUE THREAD

**Issue by Racot007** [BayatGames/JsonFormatter#1]
![image](https://user-images.githubusercontent.com/6072592/37295442-df175c4a-2620-11e8-9d13-747f45d47db4.png)
Error: TargetParameterCountException: parameters do not match signature

**Comment by hasanbayatme** [comment]
Hi, I will get back to you tomorrow and Will take a look at the issue for solving this, because here is too late.

Thanks.

**Comment by hasanbayatme** [comment]
Hi again, the issue is fixed at the latest version (this version will be published on Asset Store too, but you can download it earlier from here), [download the latest version](https://github.com/BayatGames/JsonFormatter/releases/latest) and let me know if you had any problems or questions.

Thanks.

**Comment by Racot007** [comment]
Thanks :)
